"""change scheduled_at to jsonb and add profile_picture_url

Revision ID: 1af02fe68eec
Revises: 2657f3a203fa
Create Date: 2026-06-04 16:01:31.304766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af02fe68eec'
down_revision: Union[str, Sequence[str], None] = '2657f3a203fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'sessions',
        'duration',
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False
    )

    op.alter_column(
        'sessions',
        'scheduled_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.JSONB(),
        existing_nullable=False,
        postgresql_using="to_jsonb(scheduled_at)"
    )

    op.alter_column(
        'sessions',
        'cost',
        existing_type=sa.NUMERIC(10, 2),
        type_=sa.Float(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('sessions', 'scheduled_at',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
