"""add profile_picture_url to tutor_profiles

Revision ID: 2657f3a203fa
Revises: 3faf5299b08d
Create Date: 2026-05-23 00:20:02.929355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2657f3a203fa'
down_revision: Union[str, Sequence[str], None] = '3faf5299b08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_profiles', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor_profiles', 'profile_picture_url')
    # ### end Alembic commands ###
