"""add full_name and title to tutor_profiles

Revision ID: 3faf5299b08d
Revises: c4552a929d27
Create Date: 2026-05-21 06:54:54.901788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faf5299b08d'
down_revision: Union[str, Sequence[str], None] = 'c4552a929d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index(op.f('idx_tutor_courses_course'), table_name='tutor_courses')
    op.drop_constraint(op.f('tutor_courses_tutor_id_fkey'), 'tutor_courses', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_courses', 'tutor_profiles', ['tutor_id'], ['user_id'], ondelete='CASCADE')

    # add nullable first
    op.add_column('tutor_profiles', sa.Column('full_name', sa.Text(), nullable=True))
    op.add_column('tutor_profiles', sa.Column('title', sa.Text(), nullable=True))

    # backfill existing rows
    op.execute("UPDATE tutor_profiles SET full_name = 'Unknown' WHERE full_name IS NULL")

    # enforce not null
    op.alter_column('tutor_profiles', 'full_name', nullable=False)

    op.alter_column('tutor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tutor_profiles', 'title')
    op.drop_column('tutor_profiles', 'full_name')
    op.drop_constraint(None, 'tutor_courses', type_='foreignkey')
    op.create_foreign_key(op.f('tutor_courses_tutor_id_fkey'), 'tutor_courses', 'users', ['tutor_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_tutor_courses_course'), 'tutor_courses', ['course_id'], unique=False)
    # ### end Alembic commands ###
