"""add unique constraint to userId on conversation

Revision ID: fa795c7d2e51
Revises: 1af02fe68eec
Create Date: 2026-07-16 16:47:02.800113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa795c7d2e51'
down_revision: Union[str, Sequence[str], None] = '1af02fe68eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ai_conversations', ['user_id'])
    op.drop_column('ai_conversations', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_conversations', type_='unique')
    # ### end Alembic commands ###
